# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: qmebble <qmebble@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/02/12 18:15:07 by qmebble           #+#    #+#              #
#    Updated: 2019/02/12 18:15:18 by qmebble          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FILE = fillit.c libft/ft_strlen.c check_tetriminos.c libft/ft_strsub.c libft/ft_lstnew.c libft/ft_memcpy.c libft/ft_lstadd.c generic_map.c ft_alco.c libft/ft_putchar.c
FLAGS = gcc -g  -o
NAME = fillit
all:
	$(FLAGS) fillit $(FILE)
