FILE = fillit.c libft/ft_strlen.c check_tetriminos.c libft/ft_strsub.c libft/ft_lstnew.c libft/ft_memcpy.c libft/ft_lstadd.c generic_map.c ft_alco.c
FLAGS = gcc -g  -o
NAME = fillit
all:
	$(FLAGS) fillit $(FILE)