flag = gcc 
file = get_next_line.c  libft/ft_strjoin.c libft/ft_strlen.c libft/ft_lstnew.c libft/ft_lstadd.c libft/ft_memcpy.c libft/ft_strchr.c libft/ft_strsub.c libft/ft_strdup.c libft/ft_bzero.c libft/ft_strncpy.c libft/ft_strnew.c 
all: 
	$(flag) $(file)	
